-- ============================================================================
--  Схема базы данных для бота. Запусти ОДИН РАЗ в Supabase:
--  Supabase → SQL Editor → New query → вставь это всё → Run.
--
--  Можно запускать повторно — ничего не сломается (IF NOT EXISTS).
--  Подробно — docs/01-setup.md
-- ============================================================================

-- ── ЯДРО (нужно всегда) ─────────────────────────────────────────────────────

-- Память диалога
create table if not exists chat_history (
  id          bigint generated by default as identity primary key,
  session_id  text        not null default 'default',
  role        text        not null,                 -- 'human' или 'ai'
  content     text        not null,
  created_at  timestamptz not null default now()
);
create index if not exists chat_history_session_idx
  on chat_history (session_id, created_at desc);

-- Утренние и вечерние рефлексии
create table if not exists reflections (
  id           bigint generated by default as identity primary key,
  date         date        not null default current_date,
  time_of_day  text        not null,                -- 'утро' или 'вечер'
  main_focus   text,
  priorities   jsonb,                               -- топ-3 задачи (список)
  energy       int,
  mood         text,
  win          text,
  insight      text,
  gratitude    text,
  day_rating   int,
  notes        text,
  created_at   timestamptz not null default now(),
  unique (date, time_of_day)                        -- одна запись на утро/вечер в день
);

-- Журнал отправленных чекинов (чтобы не дублировать после рестарта)
create table if not exists checkin_log (
  id          bigint generated by default as identity primary key,
  label       text        not null,
  date        text        not null,
  created_at  timestamptz not null default now()
);

-- ── ОПЦИЯ: модуль цикла (ENABLE_CYCLE) — docs/03-add-cycle.md ───────────────
create table if not exists cycle_tracking (
  id          bigint generated by default as identity primary key,
  date        date        not null default current_date,
  cycle_day   int         not null,
  notes       text,
  created_at  timestamptz not null default now()
);

-- ── ОПЦИЯ: напоминания (ENABLE_REMINDERS) — docs/06-add-reminders.md ────────
create table if not exists reminders (
  id          bigint generated by default as identity primary key,
  remind_at   timestamptz not null,
  text        text        not null,
  done        boolean     not null default false,
  created_at  timestamptz not null default now()
);

-- ── ОПЦИЯ: Google (ENABLE_GMAIL / ENABLE_GCAL) — docs/04-add-gmail.md ───────
create table if not exists oauth_tokens (
  key           text primary key,                   -- 'google'
  access_token  text,
  refresh_token text,
  expires_at    timestamptz,
  updated_at    timestamptz not null default now()
);
